<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
        <artifactId>dows-eaglee</artifactId>
    <groupId>org.dows.cloud</groupId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>eaglee-api</module>
        <module>eaglee-feign</module>
        <module>eaglee-app</module>
        <module>eaglee-boot</module>
        <module>eaglee-core</module>
        <module>eaglee-rest</module>
        <module>eaglee-service</module>
        <module>eaglee-handler</module>
        <module>eaglee-dao</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <artifactId>eaglee-api</artifactId>
                <groupId>org.dows.cloud</groupId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <artifactId>eaglee-feign</artifactId>
                <groupId>org.dows.cloud</groupId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <artifactId>eaglee-app</artifactId>
                <groupId>org.dows.cloud</groupId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <artifactId>eaglee-boot</artifactId>
                <groupId>org.dows.cloud</groupId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <artifactId>eaglee-core</artifactId>
                <groupId>org.dows.cloud</groupId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <artifactId>eaglee-rest</artifactId>
                <groupId>org.dows.cloud</groupId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <artifactId>eaglee-service</artifactId>
                <groupId>org.dows.cloud</groupId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <artifactId>eaglee-handler</artifactId>
                <groupId>org.dows.cloud</groupId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <artifactId>eaglee-dao</artifactId>
                <groupId>org.dows.cloud</groupId>
                <version>${project.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <dependencies>
    </dependencies>

</project>
